/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardContent: typeof import('./src/components/card/src/card-content.vue')['default']
    CardItem: typeof import('./src/components/card/src/card-item.vue')['default']
    ContentItem: typeof import('./src/components/card/src/content-item.vue')['default']
    DateItem: typeof import('./src/components/card/src/date-item.vue')['default']
    DirectoryItem: typeof import('./src/components/directory-item/src/directory-item.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    NavButton: typeof import('./src/components/nav/src/nav-button.vue')['default']
    NavContent: typeof import('./src/components/nav/src/nav-content.vue')['default']
    NavItem: typeof import('./src/components/nav/src/nav-item.vue')['default']
    NavMain: typeof import('./src/components/nav/src/nav-main.vue')['default']
    OperationItem: typeof import('./src/components/card/src/operation-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
